apiVersion: v1
kind: Service
metadata:
  name: node-labeler
  namespace: node-labeler
  labels:
    app.kubernetes.io/name: node-labeler
spec:
  selector:
    app.kubernetes.io/name: node-labeler
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: health
      port: 8081
      targetPort: 8081
      protocol: TCP
