apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-portal-config
  namespace: identity-portal
data:
  OIDC_ISSUER_URL: "https://keycloak.CHANGEME_DOMAIN/realms/CHANGEME_KC_REALM"
  OIDC_CLIENT_ID: "identity-portal"
  KEYCLOAK_URL: "http://keycloak.keycloak.svc.cluster.local:8080"
  KEYCLOAK_REALM: "CHANGEME_KC_REALM"
  KEYCLOAK_CLIENT_ID: "identity-portal"
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
  VAULT_SSH_MOUNT: "ssh-client-signer"
  VAULT_AUTH_ROLE: "identity-portal"
  DOMAIN: "CHANGEME_DOMAIN"
  CLUSTER_NAME: "rke2-prod"
  KUBE_API_SERVER: "https://CHANGEME_RANCHER_DOMAIN"
  ADMIN_GROUPS: "platform-admins,infra-engineers"
  VAULT_ROOT_CA_PATH: "/etc/ssl/certs/vault-root-ca.pem"
