apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    purpose: alias
spec:
  type: ClusterIP
  # Select the Operator-managed Alertmanager pods
  selector:
    app.kubernetes.io/name: alertmanager
    alertmanager: kube-prometheus-stack-alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      protocol: TCP
