apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-alerts.yaml
  - certmanager-alerts.yaml
  - cilium-alerts.yaml
  - gitlab-alerts.yaml
  - harbor-alerts.yaml
  - identity-portal-alerts.yaml
  - keycloak-alerts.yaml
  - kubernetes-alerts.yaml
  - mattermost-alerts.yaml
  - monitoring-self-alerts.yaml
  - node-alerts.yaml
  - oauth2-proxy-alerts.yaml
  - operator-alerts.yaml
  - postgresql-alerts.yaml
  - redis-alerts.yaml
  - security-alerts.yaml
  - traefik-alerts.yaml
  - vault-alerts.yaml
