# This rule is not used by the project storage-autoscaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the autoscaling.volume-autoscaler.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: storage-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: volumeautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.volume-autoscaler.io
  resources:
  - volumeautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.volume-autoscaler.io
  resources:
  - volumeautoscalers/status
  verbs:
  - get
