apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # PostgreSQL (CNPG in database namespace)
  - postgres/secret.yaml
  - postgres/keycloak-pg-cluster.yaml
  # Keycloak
  - keycloak/secret.yaml
  - keycloak/rbac.yaml
  - keycloak/deployment.yaml
  - keycloak/service.yaml
  - keycloak/service-headless.yaml
  - keycloak/hpa.yaml
  # TLS + Ingress (Gateway API + cert-manager gateway-shim)
  - gateway.yaml
  - httproute.yaml
